[package]
name = "reefdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

#dev dependencies
[dev-dependencies]
tempfile = "3.5.0"
